### ISSUE TITLE
Polarr is not showing all folders on iOS

### ISSUE THREAD

**Issue by Sorga68** [Polarrco/polarr_ios_android_support#10]
I am using Polarr on an iPad Pro, iOS 9.3.2, 128 GB, more than 20 GB free.

When trying to open a picture, the folders shown are only a subset of the picture folders on the iPad.
Please find attached the view of the Photos App and the Polarr App.

The folders I am missing are mostly synchronized folders from my Mac or empty folders. I guess the empty folders are "missing" correctly, however the synchronized folders are the ones I need to work on and that seems to be a bug.

These folders contain several hundred pictures, if that is of interest. If you need additional information please don't hesitate to contact me at steffen.ruehl@email.de

![img_0095](https://cloud.githubusercontent.com/assets/19993482/16148796/304bfad6-348c-11e6-8dee-d855b57d6d41.PNG)
![img_0096](https://cloud.githubusercontent.com/assets/19993482/16148797/306d4ba0-348c-11e6-895e-4a46acb4f2de.PNG)

**Comment by din** [comment]
Hello,

We will take a look at this issue and let you know if discover anything related to it. Thank you for the bug report!
