### ISSUE TITLE
Photo album table view scroll performance

### ISSUE THREAD

**Issue by interstateone** [Polarrco/polarr_ios_android_support#12]
In a list of ~100s of albums, the list scrolling isn't smooth at all. Other apps tend to scroll better, and the thing that stands out about Polarr's view is that it has a translucent background, and so probably transparent cell backgrounds as well. I'm guessing that the compositing that happens for these views might be causing this.

**Comment by din** [comment]
Sure, we will take a look at the performance of the photo album table view. Could you also specify the device model you are using Polarr on?

**Comment by interstateone** [comment]
Thanks! It's an iPhone 6, iOS 9.3.2.
