### ISSUE TITLE
iOS Photo Editing Extension

### ISSUE THREAD

**Issue by cdferenzi** [Polarrco/polarr_ios_android_support#14]
The Polarr Photos Extension sometimes shows the previously edited image when I try to edit within the Photos app. It won't show the correct photo until I force quit and reopen the Photos app.

**Comment by din** [comment]
Hello, thank you for the report! We will try to reproduce the issue on our side. Do you know exactly when the extension shows the previously edited image? Do you know how to reliably reproduce this?

**Comment by cdferenzi** [comment]
I'm not sure how to reliably reproduce the issue. I'm able to edit multiple
photos without any issue and then it stops. There's no set number of photos
after which is stops working. There is also a slight delay showing the new
photo when the extension functions properly.

On Thu, Jun 23, 2016 at 11:18 AM, Daniel Vershinin <notifications@github.com

**Comment by din** [comment]
We believe that we fixed the issue and the fix will arrive with the new release today (or monday). Please test it with the new release (when it hits the app store) and let us know if it is still broken. Thanks!
