### ISSUE TITLE
iOS app should offer the same aspect ratios as Mac app when cropping

### ISSUE THREAD

**Issue by interstateone** [Polarrco/polarr_ios_android_support#17]
The Mac app offers portrait and landscape orientations of each aspect ratio, which I find useful when I want to crop along a different orientation in a larger image. e.g. I want to crop a landscape image out of one originally shot in portrait. The iOS app only offers ratios for one orientation. Although they should be consistent and this could be solved multiple ways, I'd prefer to have the more numerous options of the Mac app instead of removing the additional options from it to match iOS.

Mac:
![screen shot 2016-07-09 at 7 44 42 pm](https://cloud.githubusercontent.com/assets/594059/16711237/0d48382c-460e-11e6-827c-9df9de20e4c0.png)

iOS:
![img_0412](https://cloud.githubusercontent.com/assets/594059/16711247/63333886-460e-11e6-8932-e1650e5d323c.PNG)

**Comment by bwang29** [comment]
Feature added in current version.
