### ISSUE TITLE
iOS account different from all other account versions?

### ISSUE THREAD

**Issue by ghost-bub** [Polarrco/polarr_ios_android_support#18]
My understanding is that Polarr has at least two separate account setups:

One for the Mac platform, and another for Windows/Linux/Web (Web includes Chrome version).

However, are there accounts for the mobile apps (iOS/Android)? Having downloaded a mobile version, I did not see any account info. Having this clarified would be good to understanding how to get a mobile/desktop workflow setup with Polarr.

**Comment by kpaddie** [comment]
Hi there,

There is indeed an account system for iOS/Android. However, it is not necessary to create an account to access most of the features of Polarr mobile. 

On the question of worklow: we are currently in the process of developing a unified account system that will integrate across various device platforms, so stay tuned.

Best,

-Polarr team

**Comment by ghost-bub** [comment]
Thanks! Great to hear!

**Comment by bwang29** [comment]
Account is now synced with emails when you log into different platforms.
