### ISSUE TITLE
cannot open huge pictures (Android)

### ISSUE THREAD

**Issue by pilleriin** [Polarrco/polarr_ios_android_support#19]
Hi,
I'm always taking largest pics available (up to 20MP) but Polarr cannot show them unless I make them smaller in another app.
Actually the same problem is in Win destkop app. 
I like Polarr very much but too bad cannot work with huge files.

**Comment by kpaddie** [comment]
Hi there,

Unfortunately, this is a current limitation of the application. We continue to improve and expand the application over time.

Best,

-Polarr team
