### ISSUE TITLE
Android "Open With" does not show Polarr for images (jpg)

### ISSUE THREAD

**Issue by greyandmore** [Polarrco/polarr_ios_android_support#22]
Using Android 6.0.1 with a Samsung Galaxy Tab S.
Have Polarr Installed.

When I am browsing images through any file browser and I try to open an image (such as a jpg), Polarr is not available as an option as are every other photo editing app (Aviary, PhotoShop Express, etc).  I prefer Polarr, but is frustrating that I can't use it as a default Image editing app in Android.

Am I missing something simple?
-RW

**Comment by kpaddie** [comment]
Hi RW,

Currently, "Open with Polarr" is broken. We are looking into a solution for this.

Very best,

-Polarr team
