### ISSUE TITLE
Polarr launch, photo list and album switching are very slow

### ISSUE THREAD

**Issue by DamienHarper** [Polarrco/polarr_ios_android_support#23]
Context: iCloud Photo library of around 41k photos + videos
- launching the app (previously closed) => 15s to 25s
- accessing photo table (all photos) from an edit session => 10s to 15s
- switching albums (in photo list) => 5s to 10s

The app looks very nice/powerful but these loading delays make it unusable for me at the moment unfortunately.

**Comment by kpaddie** [comment]
Hi Damien,

Thanks for your feedback. We will be working on improving loading delays for future versions.

Best,

-Polarr team
