### ISSUE TITLE
ios10.1 iPad Pro 12.9 Crash on launch

### ISSUE THREAD

**Issue by Jushiji** [Polarrco/polarr_ios_android_support#24]
I recently updated my ipad. Now it just immediately crashes on animation to fill the screen. :c
[ppe_crash.txt](https://github.com/Polarrco/polarr_ios_android_support/files/571021/ppe_crash.txt)

**Comment by kpaddie** [comment]
Hi there,
We are very sorry about this. We have received consistent crashing reports from a very small subset of our users (about 1%), across different devices, and we have been unable to determine the cause, although we continue to look into it. Some of our users have reported that the issue goes away over time on its own. If you are a paying user, you should be able to receive a refund through the App Store for this issue. We are sorry for the inconvenience. 

Best,

-Polarr team
