### ISSUE TITLE
[feature_request] uncompressed PNG or TIFF export options for iOS Polarr

### ISSUE THREAD

**Issue by skrimaging** [Polarrco/polarr_ios_android_support#26]
I just installed the latest Holiday 2016 iOS update for Polarr and was surprised to see that RAW was finally added to Polarr iOS! Huge update for my workflow!

Please add option to export edited RAW to PNG or TIFF and retain the uncompressed file system.

Recently, All iOS photo editing apps I use have implemented this very feature and has made iOS photo editing that much better! Polarr is the only one missing this.

Polarr is my go to app for noise reduction and gradient editing on iOS but can only export JPG which seems like missed oppurtunity (especially now that I can open any RAW file in it)

**Comment by skrimaging** [comment]
@seanpkent are there any plans to add TIFF export options to the iOS version of Polarr? having the ability to edit RAW is awesome but when the exported image is a JPEG, it makes it difficult to send the edited image to another app for further editing as each edit to the JPEG will make quality drop.

**Comment by seanpkent** [comment]
@skrimaging we are planning to add PNG and HIEF export in the future. We could also add TIFF but we need to test data transfer as TIFF is uncompressed and uses a lot of memory.

**Comment by skrimaging** [comment]
As long as we can get an uncompressed format out of Polarr iOS, it will be a big win.

**Comment by skrimaging** [comment]
wondering if this is still in the roadmap.

**Comment by bwang29** [comment]
PNG will be out this Friday

**Comment by NoxDineen** [comment]
Maybe the update hasn't hit Canada yet? I'm not seeing a PNG export option on iOS yet (but once I do Polarr becomes my most valuable photo app).

**Comment by skrimaging** [comment]
I too am in Canada and don’t see any Polarr update. Maybe still under review by Apple?

PNG update will really transform Polarr on iOS to a true contender to Snapseed especially with new ugly white UI Snapseed just gave us.

**Comment by bwang29** [comment]
Closing this issue. Feature existed since 4.0.0
