### ISSUE TITLE
Black margin when zooming

### ISSUE THREAD

**Issue by kpaddie** [Polarrco/polarr_ios_android_support#3]
When I zoom, I get a persistent black border to the left of the image (on iPhone 6s and iPhone SE)

<img width="335" alt="screen shot 2016-05-12 at 4 33 00 pm" src="https://cloud.githubusercontent.com/assets/13320256/15233655/3e7ecf28-185f-11e6-815a-61d130c2694c.png">

**Comment by din** [comment]
I believe this was fixed in the latest release, wasn't it?
