### ISSUE TITLE
[BUG] metadata info not applied to exported image

### ISSUE THREAD

**Issue by skrimaging** [Polarrco/polarr_ios_android_support#32]
In recent Polarr for iOS, I see a new feature to add metadata like copyright and description befoe I export image. 

Sadly, there seems to be a bug as I do not see this info in the EXIF or IPTC of exported image.. please advise.

**Comment by skrimaging** [comment]
Just installed latest update.. version 4.0 on iOS and issue still present.

**Comment by seanpkent** [comment]
@skrimaging We should have a fix soon.

**Comment by seanpkent** [comment]
@skrimaging This has been fixed so you should be seeing an update soon. Metadata from RAW images are also now fixed on iOS.

**Comment by bwang29** [comment]
Fixed, closing issue
