### ISSUE TITLE
Can't edit photos in Photo Stream on iPad 4

### ISSUE THREAD

**Issue by kpaddie** [Polarrco/polarr_ios_android_support#4]
When I try to edit photos or apply filters to photos from Photo Stream in Polarr on my iPad 4, I get this error message when I try to "Save" or "Save a Copy"
<img width="665" alt="screen shot 2016-05-12 at 4 47 50 pm" src="https://cloud.githubusercontent.com/assets/13320256/15233930/6d9806ba-1861-11e6-8a39-a91fa11d5e0e.png">

**Comment by bwang29** [comment]
This should be fixed in latest version.
