### ISSUE TITLE
Unable to use filters created on iOS with Polarr for Mac

### ISSUE THREAD

**Issue by interstateone** [Polarrco/polarr_ios_android_support#6]
I'm guessing this is a forthcoming change but the disparity between the two platforms is pretty confusing right now. iOS currently allows sharing a filter with a QR code image (or somehow with a Polarrist account, not clear), but the Mac app appears to expect a file (that isn't an image) for this purpose.

The Mac app also seems to refer to both "filters" and "presets", but it's not clear if that's a mistake or they really are distinct. Let me know if you'd like a separate issue opened in the Mac repo for this.

**Comment by bwang29** [comment]
This is coming soon for Mac end of this months. The Mac app will have a consistent UI experience with the iOS app as well. Will close this once the new Mac app is out.
