### ISSUE TITLE
Custom filters created in the iOS app don't appear and can't be imported in the photo extension

### ISSUE THREAD

**Issue by interstateone** [Polarrco/polarr_ios_android_support#7]
I've created multiple custom filters in the app, but they aren't showing up in the photo extension despite it having a custom filters section in the filter collection view. The photo extension also lacks the import button in the custom filter section, perhaps for a good reason, so the extension is currently much less usable than I would like.

**Comment by bwang29** [comment]
We're still working on filter support in the extension, as technically they're too separate apps shipped in one bundle, and we're still figuring out how to properly sync up the custom filters.
