### ISSUE TITLE
Unclear what the full-resolution support is in the iOS app

### ISSUE THREAD

**Issue by interstateone** [Polarrco/polarr_ios_android_support#8]
There's a "Disable full-resolution export" button in the settings. It's not clear what exactly this does if enabled. I.e. What is the non-full resolution when this is disabled, is there a battery life or other reason someone would disable it, etc. The wiki here also states that the app shouldn't have had full resolution support until a release sometime this month.

**Comment by bwang29** [comment]
Full resolution export allows images larger than 12MP to be exported at original resolution. When it is disabled, a 35MP image will be scaled down to 12MP when exported. Full resolution export uses more memory and is slower when turned on.
