### ISSUE TITLE
App crashes while saving photo ... and a question

### ISSUE THREAD

**Issue by douweh1** [Polarrco/polarr_ios_android_support#9]
With the new update, the app crashes when saving an edited photo. Using latest IOS version on a 6s.

question:
Is it possible to un-edit a photo? If a edit a photo from the photocell, it is marked with a bleu corner. If I reset all adjustments, it is still marked as ' edited with polarr'. 

Love the app btw  👍

**Comment by bwang29** [comment]
When the blue cell has not turned green, it means the edit hasn't been saved to the album. If you delete the photo from the album, it will also remove it from Polarr's gallery view. 

Regarding crashing, what's the size of the image were you trying to save?

**Comment by douweh1** [comment]
Thanks for your reply. It crashed with the first photo i opened, edited and saved it after the update. Later on it is only crashing on some photo's. All with photo's taken with my iPhone 6s. I already re-installed the app (and lost my own created filters :-(  ) 

I also noticed on my iPhone that the samples from my the filter packs are not rendered anymore. This was working fine before the last update.
![img_0934](https://cloud.githubusercontent.com/assets/19853033/16054277/b603bd20-326c-11e6-855f-d83d0670e1ea.PNG)

**Comment by bwang29** [comment]
This is resolved in 2 7.0
